@startuml complex_example

class "complex_example" as COMPLEX_EXAMPLE <<source>> #LightBlue
{
    - #define COMPLEX_EXAMPLE_H
    - #define MAX_ENTITIES
    - #define ENTITY_NAME_LENGTH
    - #define MAKE_COLOR
    - #define GET_RED
    - #define GET_GREEN
    - #define GET_BLUE
    - #define GET_ALPHA
}

class "entity_t" as ENTITY_T <<typedef>> #LightYellow
{
    + struct entity
}

class "data_value_t" as DATA_VALUE_T <<typedef>> #LightYellow
{
    + union data_value
}

class "event_type_t" as EVENT_TYPE_T <<typedef>> #LightYellow
{
    + enum event_type
}


@enduml