@startuml complex_example

class "complex_example" as COMPLEX_EXAMPLE <<source>> #LightBlue
{
    - #define COMPLEX_EXAMPLE_H
    - #define MAX_ENTITIES
    - #define ENTITY_NAME_LENGTH
    - #define MAKE_COLOR
    - #define GET_RED
    - #define GET_GREEN
    - #define GET_BLUE
    - #define GET_ALPHA
}


@enduml