@startuml sample

class "sample" as SAMPLE <<source>> #LightBlue
{
    - #define SAMPLE_H
    - #define PI
    - #define VERSION
    - #define MIN
    - #define MAX
    - int MAX_POINTS
}

class "point_t" as POINT_T <<typedef>> #LightYellow
{
    + struct point
}

class "system_state_t" as SYSTEM_STATE_T <<typedef>> #LightYellow
{
    + enum system_state
}

SAMPLE --> STDDEF : <<include>>

@enduml