@startuml sample

class "sample" as SAMPLE <<source>> #LightBlue
{
    - #define SAMPLE_H
    - #define PI
    - #define VERSION
    - #define MIN
    - #define MAX
    - int MAX_POINTS
}

SAMPLE --> STDDEF : <<include>>

@enduml