@startuml CLS: building

class "building" as BUILDING_C <<source>> #LightBlue
{
}

interface "stdio.h" as STDIO_H <<public_header>> #LightGreen
{
}

BUILDING_C --> STDIO_H : <<include>>

interface "building.h" as BUILDING_H <<public_header>> #LightGreen
{
    + #define BUILDING_H
    + Building create_building(const char* type, int floors)
    + void display_building(const Building* b)
}

BUILDING_C --> BUILDING_H : <<include>>

interface "string.h" as STRING_H <<public_header>> #LightGreen
{
}

BUILDING_C --> STRING_H : <<include>>


@enduml