@startuml CLS: main

class "main" as MAIN_C <<source>> #LightBlue
{
}

interface "building.h" as BUILDING_H <<public_header>> #LightGreen
{
    + #define BUILDING_H
    + Building create_building(const char* type, int floors)
    + void display_building(const Building* b)
}

MAIN_C --> BUILDING_H : <<include>>

interface "city.h" as CITY_H <<public_header>> #LightGreen
{
    + #define CITY_H
    + #define MAX_BUILDINGS 10
    + #define MAX_VEHICLES 5
    + void init_city(City* city, const char* name)
    + void add_building_to_city(City* city, Building b)
    + void add_vehicle_to_city(City* city, Vehicle v)
    + void simulate_city(const City* city)
}

MAIN_C --> CITY_H : <<include>>


@enduml