@startuml complex

class "complex" as COMPLEX <<source>> #LightBlue
{
    -- Global Variables --
    - Process_Cfg_Process_acpfct_t Process_Cfg_Process_acpfct
    - math_operation_t[10] global_math_ops
    -- Functions --
    + complex_handler_t * create_complex_handler(const char * name, ...)
    + void * create_handler(const char * name, int ( * init_func ) ( void * ) init_func, ...)
    + int execute_operations(int value, math_ops_array_t ops, int op_count)
    + math_operation_t * get_math_operations()
    + int process_with_callbacks(int[] data, int size, math_operation_t[] operations, int op_count, ...)
    + void test_processor_job_processing()
    + void test_processor_utility_macros()

    - static Std_ReturnType ProcessorAdapter_Process(const Process_T * job_pst)
    - static Std_ReturnType ProcessorHardware_Process(const Process_T * job_pst)
    - static Std_ReturnType ProcessorService_Process(const Process_T * job_pst)
    - static int add_operation(int a, int b)
    - static int divide_operation(int a, int b)
    - static void init_math_operations()
    - static int modulo_operation(int a, int b)
    - static int multiply_operation(int a, int b)
    - static void print_result(int * data, int size)
    - void run_complex_tests()
    - static int subtract_operation(int a, int b)
    - static int test_callback(int * item)
    - void test_complex_macro(int * x, int y, int z)
    - void test_handle_operation(operation_type_t op_type, int * data, int size)
    - void test_handler_table()
    - void test_mixed_union()
    - void test_operation_set()
    - void test_process_array(int * arr, int size)
    - void test_stringify_macro()
}

class "complex" as HEADER_COMPLEX <<header>> #LightGreen
{
    -- Macros --
    + #define COMPLEX_H
    + #define COMPLEX_MACRO_FUNC(x, y, z)
    + #define CREATE_FUNC_NAME(prefix, suffix)
    + #define DEPRECATED
    + #define DEPRECATED
    + #define HANDLE_OPERATION(op_type, data, size, callback)
    + #define PROCESS_ARRAY(arr, size, callback)
    + #define STRINGIFY(x)
    + #define TOSTRING(x)
    + #define UTILS_U16_TO_U8ARR_BIG_ENDIAN(value_u16, ptr_pau8)
    + #define UTILS_U32_TO_U8ARR_BIG_ENDIAN(value_u32, ptr_pau8)
    + #define UTILS_U8ARR_TO_U16_BIG_ENDIAN(ptr_pau8)
    + #define UTILS_U8ARR_TO_U32_BIG_ENDIAN(ptr_pau8)
    -- Functions --
    + complex_handler_t * create_complex_handler(const char * name, ...)
    + void * create_handler(const char * name, int ( * init_func ) ( void * ) init_func, ...)
    + int execute_operations(int value, math_ops_array_t ops, int op_count unnamed)
    + math_operation_t * get_math_operations()
    + int process_with_callbacks(int[] data, int size, math_operation_t[] operations, int op_count, ...)
    + void test_processor_job_processing()
    + void test_processor_utility_macros()
}

class "Process_T" as TYPEDEF_PROCESS_T <<struct>> #LightYellow
{
    + size_t data_size
    + char * job_data
    + int job_id
    + int priority
}

class "__anonymous_struct__" as TYPEDEF___ANONYMOUS_STRUCT__ <<struct>> #LightYellow
{
    + int level2_id
    + float level3_float
    + union {  } level3_int
}

class "array_of_anon_structs_t" as TYPEDEF_ARRAY_OF_ANON_STRUCTS_T <<struct>> #LightYellow
{
    + int count
    + float float_data
    + union {  } int_data
    + struct {  } item_id
    + char [32] item_name
    + array_of_anon_structs_t_anonymous_struct_1 y
}

class "array_of_anon_structs_t_anonymous_struct_1" as TYPEDEF_ARRAY_OF_ANON_STRUCTS_T_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
}

class "callback_with_anon_struct_t_anonymous_struct_1" as TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
    + int config_flags
    + char[64] config_name
    + } config_value
    + float float_config
    + union { int int_config
}

class "complex_callback_t_anonymous_struct_1" as TYPEDEF_COMPLEX_CALLBACK_T_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
    + int nested1
    + char * nested2
    + void(* nested_func)(int) nested_func
}

class "complex_handler_t" as TYPEDEF_COMPLEX_HANDLER_T <<struct>> #LightYellow
{
    + void(* format_func)(char * , int) format_func
    + int id
    + int(* validate_func)(const char *) validate_func
}

class "complex_naming_test_t" as TYPEDEF_COMPLEX_NAMING_TEST_T <<struct>> #LightYellow
{
    + struct {  } deep_a1
    + struct {  } first_a
    + struct {  } nested_a1
}

class "config_param" as TYPEDEF_CONFIG_PARAM <<struct>> #LightYellow
{
    + int config_flags
    + char [64] config_name
    + float float_config
    + union {  } int_config
}

class "data_item_t" as TYPEDEF_DATA_ITEM_T <<struct>> #LightYellow
{
    + char * name
    + int value
}

class "data_union_anonymous_struct_1" as TYPEDEF_DATA_UNION_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
}

class "extreme_nesting_test_t" as TYPEDEF_EXTREME_NESTING_TEST_T <<struct>> #LightYellow
{
    + struct { { } level4_field
}

class "handler_entry_t" as TYPEDEF_HANDLER_ENTRY_T <<struct>> #LightYellow
{
    + void(* cleanup_func)(void) cleanup_func
    + int id
    + void(* init_func)(void) init_func
    + char [16] name
    + int(* process_func)(int , int) process_func
}

class "item_value_anonymous_struct_1" as TYPEDEF_ITEM_VALUE_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
}

class "moderately_nested_t" as TYPEDEF_MODERATELY_NESTED_T <<struct>> #LightYellow
{
    + int level1_id
    + struct {  } level2_id
    + float level3_float
    + union {  } level3_int
}

class "multi_anonymous_t" as TYPEDEF_MULTI_ANONYMOUS_T <<struct>> #LightYellow
{
    + struct {  } first_x
    + int first_y
}

class "multiple_simple_anonymous_t" as TYPEDEF_MULTIPLE_SIMPLE_ANONYMOUS_T <<struct>> #LightYellow
{
    + struct {  } first_field
}

class "operation_set_t" as TYPEDEF_OPERATION_SET_T <<struct>> #LightYellow
{
    + void(* callbacks[3])(int , char *) callbacks
    + int count
    + math_operation_t [5] operations
}

class "param4" as TYPEDEF_PARAM4 <<struct>> #LightYellow
{
    + int nested1
    + char * nested2
    + void(* nested_func)(int) nested_func
}

class "processor_t" as TYPEDEF_PROCESSOR_T <<struct>> #LightYellow
{
    + void(* cleanup_func)(void *) cleanup_func
    + int id
    + char [64] name
    + int(* process_func)(int , char *) process_func
}

class "result_generator_t" as TYPEDEF_RESULT_GENERATOR_T <<struct>> #LightYellow
{
    + char [128] error_message
    + int result_code
    + union {  } success_value
}

class "simplified_handler_t" as TYPEDEF_SIMPLIFIED_HANDLER_T <<struct>> #LightYellow
{
    + int event_count
    + int event_flags
    + char [32] event_name
}

class "struct_with_struct_t" as TYPEDEF_STRUCT_WITH_STRUCT_T <<struct>> #LightYellow
{
    + char [16] inner_label
    + struct {  } inner_x
    + int inner_y
    + int outer_id
    + char [32] outer_name
}

class "struct_with_union_t" as TYPEDEF_STRUCT_WITH_UNION_T <<struct>> #LightYellow
{
    + float float_value
    + union {  } int_value
    + char [64] string_value
    + int type_id
    + struct_with_union_t_anonymous_struct_1 z
}

class "struct_with_union_t_anonymous_struct_1" as TYPEDEF_STRUCT_WITH_UNION_T_ANONYMOUS_STRUCT_1 <<struct>> #LightYellow
{
}

class "operation_type_t" as TYPEDEF_OPERATION_TYPE_T <<enumeration>> #LightYellow
{
    OP_ADD = 0
    OP_DIV = 3
    OP_MUL = 2
    OP_SUB = 1
}

class "processor_module_enum_t" as TYPEDEF_PROCESSOR_MODULE_ENUM_T <<enumeration>> #LightYellow
{
    PROCESSOR_CFG_MODULE_ADAPTER = 0
    PROCESSOR_CFG_MODULE_COUNT = 3
    PROCESSOR_CFG_MODULE_HARDWARE = 2
    PROCESSOR_CFG_MODULE_SERVICE = 1
}

class "Process_Cfg_Process_acpfct_t" as TYPEDEF_PROCESS_CFG_PROCESS_ACPFCT_T <<typedef>> #LightYellow
{
    alias of Process_Cfg_Process_fct Process_Cfg_Process_acpfct_t[PROCESSOR_CFG_MODULE_COUNT]
}

class "Process_Cfg_Process_fct" as TYPEDEF_PROCESS_CFG_PROCESS_FCT <<function pointer>> #LightYellow
{
    alias of Std_ReturnType(* Process_Cfg_Process_fct)(const Process_T * job_pst)
}

class "Std_ReturnType" as TYPEDEF_STD_RETURNTYPE <<typedef>> #LightYellow
{
    alias of int
}

class "callback_with_anon_struct_t" as TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T <<function pointer>> #LightYellow
{
    alias of void(* callback_with_anon_struct_t)( int id , struct { int config_flags ; char config_name [ 64 ] ; callback_with_anon_struct_t_anonymous_union_2 config_value ; } * config_param , void * user_data )
}

class "complex_callback_t" as TYPEDEF_COMPLEX_CALLBACK_T <<function pointer>> #LightYellow
{
    alias of int(* complex_callback_t)( int param1 , char * param2 , void * param3 , complex_callback_t_anonymous_struct_1 * param4 )
}

class "complex_func_ptr_t" as TYPEDEF_COMPLEX_FUNC_PTR_T <<typedef>> #LightYellow
{
    alias of int ( * ( * complex_func_ptr_t ) ( int , char * ) ) ( double , void * )
}

class "data_processor_array_t" as TYPEDEF_DATA_PROCESSOR_ARRAY_T <<typedef>> #LightYellow
{
    alias of data_processor_t *
}

class "data_processor_t" as TYPEDEF_DATA_PROCESSOR_T <<function pointer>> #LightYellow
{
    alias of int(* data_processor_t)(data_item_t * item , void * context)
}

class "debug_callback_t" as TYPEDEF_DEBUG_CALLBACK_T <<function pointer>> #LightYellow
{
    alias of void(* debug_callback_t)(const char * message , int level)
}

class "handler_table_t" as TYPEDEF_HANDLER_TABLE_T <<typedef>> #LightYellow
{
    alias of handler_entry_t handler_table_t[8]
}

class "math_operation_t" as TYPEDEF_MATH_OPERATION_T <<function pointer>> #LightYellow
{
    alias of int(* math_operation_t)(int , int)
}

class "math_ops_array_t" as TYPEDEF_MATH_OPS_ARRAY_T <<typedef>> #LightYellow
{
    alias of math_operation_t math_ops_array_t[10]
}

class "release_callback_t" as TYPEDEF_RELEASE_CALLBACK_T <<function pointer>> #LightYellow
{
    alias of void(* release_callback_t)(const char * message)
}

class "uint16" as TYPEDEF_UINT16 <<typedef>> #LightYellow
{
    alias of uint16_t
}

class "uint32" as TYPEDEF_UINT32 <<typedef>> #LightYellow
{
    alias of uint32_t
}

class "uint8" as TYPEDEF_UINT8 <<typedef>> #LightYellow
{
    alias of uint8_t
}

class "callback_with_anon_struct_t_anonymous_union_2" as TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T_ANONYMOUS_UNION_2 <<union>> #LightYellow
{
    + float float_config
    + int int_config
}

class "config_value" as TYPEDEF_CONFIG_VALUE <<union>> #LightYellow
{
    + float float_config
    + int int_config
}

class "data_union" as TYPEDEF_DATA_UNION <<union>> #LightYellow
{
    + float float_value
    + int int_value
    + char [64] string_value
    + data_union_anonymous_struct_1 z
}

class "first_anon_union" as TYPEDEF_FIRST_ANON_UNION <<union>> #LightYellow
{
    + float union_float
    + int union_int
}

class "first_union" as TYPEDEF_FIRST_UNION <<union>> #LightYellow
{
    + int union_field1
}

class "item_value" as TYPEDEF_ITEM_VALUE <<union>> #LightYellow
{
    + float float_data
    + int int_data
    + item_value_anonymous_struct_1 y
}

class "level3_union" as TYPEDEF_LEVEL3_UNION <<union>> #LightYellow
{
    + float level3_float
    + int level3_int
}

class "mixed_union" as TYPEDEF_MIXED_UNION <<union>> #LightYellow
{
    + struct {  } mixed_field
}

class "mixed_union_t" as TYPEDEF_MIXED_UNION_T <<union>> #LightYellow
{
    + int(* int_func)(int) int_func
    + int int_val
    + char * str_val
    + void(* void_func)(void) void_func
}

class "result_data" as TYPEDEF_RESULT_DATA <<union>> #LightYellow
{
    + char [128] error_message
    + int success_value
}

class "second_union" as TYPEDEF_SECOND_UNION <<union>> #LightYellow
{
    + int union_field2
}

class "struct_union" as TYPEDEF_STRUCT_UNION <<union>> #LightYellow
{
    + int struct_union_int
    + struct {  } struct_union_struct_field
}

class "union_with_struct_t" as TYPEDEF_UNION_WITH_STRUCT_T <<union>> #LightYellow
{
    + struct {  } error_code
    + char [128] error_msg
    + void * payload_data
    + int payload_size
    + float simple_float
    + int simple_int
}

class "union_with_union_t" as TYPEDEF_UNION_WITH_UNION_T <<union>> #LightYellow
{
    + union {  } deep_char
    + short deep_short
    + double nested_double
    + union {  } nested_float
    + int primary_int
}


' Include relationships
COMPLEX --> HEADER_COMPLEX : <<include>>

' Declaration relationships
HEADER_COMPLEX ..> TYPEDEF_PROCESS_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF___ANONYMOUS_STRUCT__ : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_ARRAY_OF_ANON_STRUCTS_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_ARRAY_OF_ANON_STRUCTS_T_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_COMPLEX_CALLBACK_T_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_COMPLEX_HANDLER_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_COMPLEX_NAMING_TEST_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_CONFIG_PARAM : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DATA_ITEM_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DATA_UNION_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_EXTREME_NESTING_TEST_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_HANDLER_ENTRY_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_ITEM_VALUE_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MODERATELY_NESTED_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MULTI_ANONYMOUS_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MULTIPLE_SIMPLE_ANONYMOUS_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_OPERATION_SET_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_PARAM4 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_PROCESSOR_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_RESULT_GENERATOR_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_SIMPLIFIED_HANDLER_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_STRUCT_WITH_STRUCT_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_STRUCT_WITH_UNION_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_STRUCT_WITH_UNION_T_ANONYMOUS_STRUCT_1 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_OPERATION_TYPE_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_PROCESSOR_MODULE_ENUM_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_PROCESS_CFG_PROCESS_ACPFCT_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_PROCESS_CFG_PROCESS_FCT : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_STD_RETURNTYPE : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_COMPLEX_CALLBACK_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_COMPLEX_FUNC_PTR_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DATA_PROCESSOR_ARRAY_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DATA_PROCESSOR_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DEBUG_CALLBACK_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_HANDLER_TABLE_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MATH_OPERATION_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MATH_OPS_ARRAY_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_RELEASE_CALLBACK_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_UINT16 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_UINT32 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_UINT8 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T_ANONYMOUS_UNION_2 : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_CONFIG_VALUE : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_DATA_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_FIRST_ANON_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_FIRST_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_ITEM_VALUE : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_LEVEL3_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MIXED_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_MIXED_UNION_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_RESULT_DATA : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_SECOND_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_STRUCT_UNION : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_UNION_WITH_STRUCT_T : <<declares>>
HEADER_COMPLEX ..> TYPEDEF_UNION_WITH_UNION_T : <<declares>>

' Uses relationships
TYPEDEF_ARRAY_OF_ANON_STRUCTS_T ..> TYPEDEF_ARRAY_OF_ANON_STRUCTS_T_ANONYMOUS_STRUCT_1 : <<uses>>
TYPEDEF_OPERATION_SET_T ..> TYPEDEF_MATH_OPERATION_T : <<uses>>
TYPEDEF_STRUCT_WITH_UNION_T ..> TYPEDEF_STRUCT_WITH_UNION_T_ANONYMOUS_STRUCT_1 : <<uses>>
TYPEDEF_PROCESS_CFG_PROCESS_ACPFCT_T ..> TYPEDEF_PROCESS_CFG_PROCESS_FCT : <<uses>>
TYPEDEF_PROCESS_CFG_PROCESS_FCT ..> TYPEDEF_PROCESS_T : <<uses>>
TYPEDEF_PROCESS_CFG_PROCESS_FCT ..> TYPEDEF_STD_RETURNTYPE : <<uses>>
TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T ..> TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T_ANONYMOUS_UNION_2 : <<uses>>
TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T ..> TYPEDEF_CONFIG_PARAM : <<uses>>
TYPEDEF_CALLBACK_WITH_ANON_STRUCT_T ..> TYPEDEF_CONFIG_VALUE : <<uses>>
TYPEDEF_COMPLEX_CALLBACK_T ..> TYPEDEF_COMPLEX_CALLBACK_T_ANONYMOUS_STRUCT_1 : <<uses>>
TYPEDEF_COMPLEX_CALLBACK_T ..> TYPEDEF_PARAM4 : <<uses>>
TYPEDEF_DATA_PROCESSOR_ARRAY_T ..> TYPEDEF_DATA_PROCESSOR_T : <<uses>>
TYPEDEF_DATA_PROCESSOR_T ..> TYPEDEF_DATA_ITEM_T : <<uses>>
TYPEDEF_HANDLER_TABLE_T ..> TYPEDEF_HANDLER_ENTRY_T : <<uses>>
TYPEDEF_MATH_OPS_ARRAY_T ..> TYPEDEF_MATH_OPERATION_T : <<uses>>

@enduml