@startuml logger

class "logger" as LOGGER <<source>> #LightBlue
{
    -- Global Variables --
    - log_callback_t current_cb
    -- Functions --
    + void log_message(log_level_t level, const char * fmt, ...)
    + void set_log_callback(log_callback_t cb)
}

class "config" as HEADER_CONFIG <<header>> #LightGreen
{
    -- Macros --
    + #define CONFIG_H
    + #define DEFAULT_BUFFER_SIZE
    + #define MAX_LABEL_LEN
    + #define PROJECT_NAME
}

class "logger" as HEADER_LOGGER <<header>> #LightGreen
{
    -- Macros --
    + #define LOGGER_H
    -- Functions --
    + void log_message(log_level_t level, const char * fmt, ...)
    + void set_log_callback(log_callback_t cb)
}

class "GlobalStatus" as TYPEDEF_GLOBALSTATUS <<enumeration>> #LightYellow
{
    GS_ERROR
    GS_OK
    GS_UNKNOWN
}

class "id_t" as TYPEDEF_ID_T <<typedef>> #LightYellow
{
    alias of uint32_t
}

class "status_t" as TYPEDEF_STATUS_T <<typedef>> #LightYellow
{
    alias of int32_t
}

class "log_level_t" as TYPEDEF_LOG_LEVEL_T <<enumeration>> #LightYellow
{
    LOG_DEBUG = 0
    LOG_ERROR
    LOG_INFO
    LOG_WARN
}

class "log_callback_t" as TYPEDEF_LOG_CALLBACK_T <<typedef>> #LightYellow
{
    alias of void(* log_callback_t)(log_level_t level , const char * message)
}


' Include relationships
LOGGER --> HEADER_LOGGER : <<include>>
HEADER_LOGGER --> HEADER_CONFIG : <<include>>

' Declaration relationships
HEADER_CONFIG ..> TYPEDEF_GLOBALSTATUS : <<declares>>
HEADER_CONFIG ..> TYPEDEF_ID_T : <<declares>>
HEADER_CONFIG ..> TYPEDEF_STATUS_T : <<declares>>
HEADER_LOGGER ..> TYPEDEF_LOG_LEVEL_T : <<declares>>
HEADER_LOGGER ..> TYPEDEF_LOG_CALLBACK_T : <<declares>>

' Uses relationships
TYPEDEF_LOG_CALLBACK_T ..> TYPEDEF_LOG_LEVEL_T : <<uses>>

@enduml