name: "02. PlantUML to PNG"

on:
  workflow_dispatch:
    inputs:
      output_folder:
        description: 'Output folder containing .puml files'
        required: false
        default: 'output'
        type: string
  workflow_call:
    inputs:
      output_folder:
        description: 'Output folder containing .puml files'
        required: false
        type: string

jobs:
  generate-plantuml:
    runs-on: ubuntu-latest
    concurrency:
      group: "plantuml-generation"
      cancel-in-progress: true
    permissions:
      contents: write
      actions: write
    
    steps:
    - name: "02.01 Checkout code"
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN || github.token }}

    - name: "02.02 Setup Git configuration"
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: "02.03 Install system dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz default-jre

    - name: "02.04 Setup PlantUML"
      run: |
        if [ ! -f "plantuml.jar" ]; then
          wget https://github.com/plantuml/plantuml/releases/download/v1.2024.0/plantuml-1.2024.0.jar -O plantuml.jar
        fi
        java -jar plantuml.jar -testdot

    - name: "02.05 Generate PNG images"
      run: |
        echo "🚀 Running PlantUML to PNG conversion..."
        chmod +x ./scripts/picgen.sh
        ./scripts/picgen.sh
        
        if [ ! -f "artifacts/output_example/diagram_index.html" ]; then
          echo "❌ Error: diagram_index.html was not generated"
          exit 1
        fi
        echo "✅ diagram_index.html was successfully generated"

    - name: "02.06 Commit generated images"
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "📝 Committing generated images..."
        
        git add artifacts/output_example/*.png 2>/dev/null || echo "No new PNG images"
        git add artifacts/output_example/diagram_index.html 2>/dev/null || echo "No diagram index"
        git add -A
        
        if ! git diff --cached --quiet; then
          git commit -m "Auto-generate PlantUML PNG images and diagram index - run #${{ github.run_number }}"
          git pull origin ${{ github.ref }} --rebase || git pull origin ${{ github.ref }}
          git push origin ${{ github.ref }}
          
          echo "✅ Successfully committed and pushed generated images"
        else
          echo "ℹ️ No changes to commit"
        fi

    - name: "02.07 Upload generated images as artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: plantuml-png-images
        path: |
          artifacts/output_example/*.png
          artifacts/output_example/diagram_index.html
        retention-days: 30

    - name: "02.08 Trigger website deployment"
      if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: actions/github-script@v7
      with:
        script: |
          console.log('🚀 Triggering website deployment...');
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: '03-deploy-website.yml',
            ref: context.ref,
            inputs: {
              message: `Deploy after PlantUML generation - run #${context.runNumber}`
            }
          });